# PyTorch 개론 (+Google Colab 사용법)
<hr>

cf. Google Colab: [[링크](https://colab.research.google.com/notebooks/welcome.ipynb)] [[사용법](https://drive.google.com/file/d/11B7cjkW0KVMZv-yqxHDhg0TUE3CESYSx/view)]

## 0. Basic Python

### 0.1 자료형과 연산

#### 숫자형

In [1]:
a = 10
b = 1.2
print(a, b)
print(a+b, a-b, a*b, a/b)

10 1.2
11.2 8.8 12.0 8.333333333333334


#### 문자열

In [2]:
quote = "Life is too short,"
print(quote, "Python is fast") 

Life is too short, Python is fast


#### 리스트 / 튜플

* 리스트

In [3]:
a = [1, 2, 'Life', ['a', 'b', 'c']]

In [4]:
print(a[0]) 

1


In [5]:
print(a[-1]) 


['a', 'b', 'c']


In [6]:
print(a[-1][1]) 

b


In [7]:
print(a[0:2]) 

[1, 2]


In [8]:
a.append('short') 
a.insert(2, 3)
print(a)

[1, 2, 3, 'Life', ['a', 'b', 'c'], 'short']


* 튜플: 리스트와 비슷하지만 요소값 생성, 삭제, 수정이 불가

#### 딕셔너리 / 집합

In [9]:
dic = {'key': 'value', '류현진': '야구', '손흥민': '축구'}

In [10]:
print(dic['류현진']) 

야구


In [11]:
print(dic.keys())

dict_keys(['key', '류현진', '손흥민'])


In [12]:
print(dic.values())

dict_values(['value', '야구', '축구'])


In [13]:
dic['new key'] = 'new value' 
print(dic)

{'key': 'value', '류현진': '야구', '손흥민': '축구', 'new key': 'new value'}


### 0.2 제어문

#### if 문

In [14]:
a = [1,2,3]
if a[1]%2==0:
    print("{} is even number".format(a[1]))
elif a[1]%2==1:
    print("{} is odd number".format(a[1]))
else:
    print("Impossible")

2 is even number


#### for 문

In [15]:
for i in range(0, 3):
    print(i)

0
1
2


#### while 문

In [16]:
a = 0
while True:
    if a == 3:
        break
    print(a) 
    a +=1

0
1
2


### 0.3 함수 / 클래스

#### 함수

In [17]:
def square_sum(a, b):
    squared_a = a**2
    squared_b = b**2
    return squared_a + squared_b

c = square_sum(3, 4)
print(c)

25


#### 클래스 

In [18]:
class Calculator():
    def __init__(self):
        self.description = "Example for initializing a Class"
        self.result = 0

    def add(self, numb1, numb2):
        if type(numb1) == int and type(numb2) == int:
            result = numb1 + numb2
            return result
        else:
            raise Exception

cal = Calculator()
print(cal.description)
print(cal.add(10, 20))

Example for initializing a Class
30


### 0.4 Packages

#### import

In [19]:
import numpy as np
a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


<hr>

## 1. PyTorch

### 1.1 Tensors / Numpy

In [20]:
import torch
import numpy as np

#### Tensors / Numpy / Python List
* Python List: 행렬연산을 위해 for 문을 사용  
* Numpy: 조건에 따라 차원이 다른 배열간의 연산을 가능하게 하는 Broadcasting을 사용하여 연산가능  
* Tensor: pytorch의 자료형으로 numpy배열과 비슷하나, GPU에서의 연산이 가능하고, Pytorch의 Autograd(자동미분) 연산 가능 [[참고](https://blog.naver.com/PostView.nhn?blogId=qbxlvnf11&logNo=221558405051)]

#### Tensors 초기화

In [21]:
# 초기화 되지 않은 행렬 생성
x = torch.empty(5, 3)
print(x)

tensor([[4.6894e+27, 7.9463e+08, 3.2604e-12],
        [1.7743e+28, 2.0535e-19, 5.9682e-02],
        [7.0374e+22, 3.8946e+21, 4.4650e+30],
        [7.0975e+22, 7.9309e+34, 7.9439e+08],
        [3.2604e-12, 7.3113e+34, 2.0706e-19]])


In [22]:
# 0~1 사이에서 랜덤으로 초기화된 행렬 생성
x = torch.rand(5, 3)
print(x)

tensor([[0.8128, 0.8355, 0.2968],
        [0.2276, 0.5474, 0.7757],
        [0.9524, 0.0985, 0.4289],
        [0.9102, 0.1175, 0.6893],
        [0.1119, 0.6819, 0.0299]])


In [23]:
# Standard Normal Distribution 에서 랜덤으로 초기화된 행렬 생성
x = torch.randn(5, 3)
print(x)

tensor([[ 0.4450, -0.7445, -1.5350],
        [ 0.1467,  0.2402,  0.8348],
        [-1.1527, -0.7043, -0.3576],
        [-0.0708,  0.3321, -0.5246],
        [-0.3378,  1.1601,  1.4401]])


In [24]:
# 값 지정하여 행렬 생성
x = torch.tensor([1.2, 2.4])
print(x)

tensor([1.2000, 2.4000])


#### Tensor 연산

In [25]:
# 덧셈
x = torch.randn(5, 3)
y = torch.randn(5, 3)
print(x, '\n', y, '\n', x+y) # x+y = torch.add(x, y)

tensor([[-0.1455, -0.7607,  0.8373],
        [-0.1988,  1.6557,  1.5501],
        [ 1.2742, -1.1550, -0.8316],
        [ 0.1673, -1.2299,  0.2246],
        [ 0.4496, -0.1102,  0.2130]]) 
 tensor([[-0.3422,  0.7117,  0.1839],
        [-1.1631, -0.6214, -0.4986],
        [-0.9649,  1.1657,  0.9962],
        [ 0.0656,  0.4938,  0.8723],
        [-0.4114, -0.8063,  0.2738]]) 
 tensor([[-0.4877, -0.0490,  1.0213],
        [-1.3619,  1.0343,  1.0515],
        [ 0.3093,  0.0106,  0.1646],
        [ 0.2329, -0.7361,  1.0969],
        [ 0.0382, -0.9165,  0.4868]])


#### Tensor 사이즈

In [26]:
# Size 확인
x = torch.randn(4, 4)
print(x.size())

torch.Size([4, 4])


In [27]:
# Resize - view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

# Resize - reshape

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### Tensor, Numpy 변환

In [28]:
# Tensor to Numpy
a = torch.ones(5)
b = a.numpy()
print(a, type(a))
print(b, type(b))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [29]:
# Numpy to Tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a, type(a))
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [30]:
# GPU 연산을 위한 CUDA Tensor
a = torch.ones(5)
# b = a.to(device="cudo:0")

#### Tensor Autograd  
requires_grad 를 true로 세팅하면, 텐서의 모든 연산에 대한 추적 가능  
이를 통해 forward propagation 후 .backward() 호출 시 모든 gradient를 자동으로 계산

In [31]:
x = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True) # default requires_grad for input data: False (whereas default requires_grad for each layer is True)
y = (x+2)**2*3
print(y)

out = y.mean()
print(out)

out.backward()
print(x.grad)

tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)
tensor(64.5000, grad_fn=<MeanBackward0>)
tensor([[4.5000, 6.0000],
        [7.5000, 9.0000]])


$\because {dout\over dx_i} = {dout \over dy} * {dy \over dx_i} = {1 \over 4}*6(x_i+2) = {3\over2}(x_i+2) \hspace{1cm}$
as ${dout \over dy} = {1 \over 4}, {dy \over dx_i} = 6(x_i+2)$

### 1.2 PyTorch Project 구조

#### 1. Load Data

In [32]:
import torchvision # to download 'CIFAR10' dataset
import torchvision.transforms as transforms # to manipulate input data

In [33]:
train_data = torchvision.datasets.CIFAR10(root='./datasets', 
                                          train=True, 
                                          transform=transforms.ToTensor(), 
                                          download=True)

Files already downloaded and verified


In [34]:
# cf) check for the data
image, label = train_data[0]
print(len(train_data), image.size(), label)

50000 torch.Size([3, 32, 32]) 6


#### 2. Define Dataloader
define dataloader (when iters loop, dataloader loads data from queue)

In [35]:
import torch

In [36]:
data_loader = torch.utils.data.DataLoader(dataset=train_data, 
                                          batch_size=64,
                                          shuffle=True)

In [37]:
# cf) check how data_loader works
print(len(data_loader))
for idx, (images, labels) in enumerate(data_loader):
    if idx == 3:
        break
    print(images.size(), labels)

782
torch.Size([64, 3, 32, 32]) tensor([6, 3, 4, 1, 5, 1, 4, 5, 8, 5, 2, 9, 9, 3, 9, 0, 5, 7, 9, 5, 9, 7, 9, 6,
        2, 6, 7, 4, 2, 9, 1, 5, 0, 5, 4, 3, 0, 1, 2, 6, 4, 4, 4, 9, 8, 3, 3, 1,
        8, 3, 5, 5, 3, 7, 1, 0, 2, 9, 6, 3, 4, 8, 5, 0])
torch.Size([64, 3, 32, 32]) tensor([2, 7, 8, 9, 6, 1, 5, 4, 6, 4, 7, 0, 4, 7, 2, 9, 6, 5, 0, 4, 5, 2, 3, 4,
        1, 8, 9, 2, 3, 6, 9, 6, 8, 5, 7, 0, 0, 5, 5, 2, 7, 2, 0, 1, 7, 3, 4, 4,
        6, 7, 6, 5, 0, 6, 1, 4, 4, 8, 0, 5, 6, 1, 3, 8])
torch.Size([64, 3, 32, 32]) tensor([8, 2, 9, 6, 7, 1, 8, 5, 8, 5, 7, 0, 0, 6, 1, 1, 6, 4, 9, 6, 4, 3, 7, 6,
        2, 5, 9, 8, 6, 5, 0, 2, 0, 2, 1, 8, 0, 0, 0, 7, 7, 2, 6, 0, 2, 8, 0, 2,
        2, 9, 0, 3, 5, 6, 9, 6, 5, 2, 3, 2, 6, 2, 6, 0])


#### 3. Define Model

In [38]:
import torch.nn as nn
import torch.nn.functional as F

In [39]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(3, 6, 5),
            nn.BatchNorm2d(6),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)
        )
        self.fc = nn.Linear(6*14*14, 10) # 10 final nodes as CIFAR10 dataset has 10 classes
    
    def forward(self, x):
        out = self.layer1(x)
        out = out.reshape(out.size(0), -1)
        out = self.fc(out)
        return out
    
model = Net()

In [40]:
# cf) check which layers constitute Network
print(model)

Net(
  (layer1): Sequential(
    (0): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
    (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc): Linear(in_features=1176, out_features=10, bias=True)
)


In [41]:
# cf) check how data passes through the Network
data_iter = iter(data_loader)
images, labels = data_iter.next() # only get one mini-batch
outputs = model(images)
print(outputs.size(), '\n', outputs[0], '\n', outputs[0].tolist().index(max(outputs[0])))

torch.Size([64, 10]) 
 tensor([ 0.6421, -1.2926, -0.9401,  0.8215, -1.4360,  1.4673, -1.2807, -0.8465,
         0.9355, -1.8001], grad_fn=<SelectBackward>) 
 5


#### 4. Set Loss & Optimizer

In [42]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

#### 5. Train / Test

In [43]:
epochs = 1
for epoch in range(epochs):
    for i, (images, labels) in enumerate(data_loader):
        # Forward Propagate
        outputs = model(images)
        
        # Get Loss, Compute Gradient, Update Parameters
        loss = criterion(outputs, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if i%50 == 0 or i+1==len(data_loader):
            print('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'.format(epoch+1, epochs, i+1, len(data_loader), loss.item()))
        

Epoch [1/1], Step [1/782], Loss: 2.3333
Epoch [1/1], Step [51/782], Loss: 2.2852
Epoch [1/1], Step [101/782], Loss: 2.1661
Epoch [1/1], Step [151/782], Loss: 2.2380
Epoch [1/1], Step [201/782], Loss: 2.1518
Epoch [1/1], Step [251/782], Loss: 2.1738
Epoch [1/1], Step [301/782], Loss: 2.0543
Epoch [1/1], Step [351/782], Loss: 2.0390
Epoch [1/1], Step [401/782], Loss: 2.0817
Epoch [1/1], Step [451/782], Loss: 2.0555
Epoch [1/1], Step [501/782], Loss: 2.0291
Epoch [1/1], Step [551/782], Loss: 2.0639
Epoch [1/1], Step [601/782], Loss: 2.2059
Epoch [1/1], Step [651/782], Loss: 2.1244
Epoch [1/1], Step [701/782], Loss: 2.1475
Epoch [1/1], Step [751/782], Loss: 1.9754
Epoch [1/1], Step [782/782], Loss: 2.2998


#### 6. Save & Visualization

In [44]:
torch.save(model.state_dict(), 'model.ckpt')

In [45]:
# cf) check the saved model
!ls

datasets            intro_pytorch.ipynb model.ckpt


<hr>