# PyTorch 개론 (+Google Colab 사용법)
<hr>

cf. Google Colab: [[링크](https://colab.research.google.com/notebooks/welcome.ipynb)] [[사용법](https://drive.google.com/file/d/11B7cjkW0KVMZv-yqxHDhg0TUE3CESYSx/view)]

## 0. Basic Python

### 0.1 자료형과 연산

#### 숫자형

In [1]:
a = 10
b = 1.2
print(a, b)
print(a+b, a-b, a*b, a/b)

10 1.2
11.2 8.8 12.0 8.333333333333334


#### 문자열

In [2]:
quote = "Life is too short,"
print(quote, "Python is fast") 

Life is too short, Python is fast


#### 리스트 / 튜플

* 리스트

In [3]:
a = [1, 2, 'Life', ['a', 'b', 'c']]

In [4]:
print(a[0]) 

1


In [5]:
print(a[-1]) 


['a', 'b', 'c']


In [6]:
print(a[-1][1]) 

b


In [7]:
print(a[0:2]) 

[1, 2]


In [8]:
a.append('short') 
a.insert(2, 3)
print(a)

[1, 2, 3, 'Life', ['a', 'b', 'c'], 'short']


* 튜플: 리스트와 비슷하지만 요소값 생성, 삭제, 수정이 불가

#### 딕셔너리

In [9]:
dic = {'key': 'value', '류현진': '야구', '손흥민': '축구'}

In [10]:
print(dic['류현진']) 

야구


In [11]:
print(dic.keys())

dict_keys(['key', '류현진', '손흥민'])


In [12]:
print(dic.values())

dict_values(['value', '야구', '축구'])


In [13]:
dic['new key'] = 'new value' 
print(dic)

{'key': 'value', '류현진': '야구', '손흥민': '축구', 'new key': 'new value'}


### 0.2 제어문

#### if 문

In [14]:
a = [1,2,3]
if a[1]%2==0:
    print("{} is even number".format(a[1]))
elif a[1]%2==1:
    print("{} is odd number".format(a[1]))
else:
    print("Impossible")

2 is even number


#### for 문

In [15]:
for i in range(0, 3):
    print(i)

0
1
2


#### while 문

In [16]:
a = 0
while True:
    if a == 3:
        break
    print(a) 
    a +=1

0
1
2


### 0.3 함수 / 클래스

#### 함수

In [17]:
def square_sum(a, b):
    squared_a = a**2
    squared_b = b**2
    return squared_a + squared_b

c = square_sum(3, 4)
print(c)

25


#### 클래스 

In [18]:
class Calculator():
    def __init__(self):
        self.description = "Example for initializing a Class"
        self.result = 0

    def add(self, numb1, numb2):
        if type(numb1) == int and type(numb2) == int:
            result = numb1 + numb2
            return result
        else:
            raise Exception

cal = Calculator()
print(cal.description)
print(cal.add(10, 20))

Example for initializing a Class
30


### 0.4 Packages

#### import

In [19]:
import numpy as np
a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


<hr>

## 1. PyTorch

### 1.1 Tensors / Numpy

In [20]:
import torch
import numpy as np

#### Tensors / Numpy / Python List
* Python List: 행렬연산을 위해 for 문을 사용  
* Numpy: 조건에 따라 차원이 다른 배열간의 연산을 가능하게 하는 Broadcasting을 사용하여 연산가능  
* Tensor: pytorch의 자료형으로 numpy배열과 비슷하나, GPU에서의 연산이 가능하고, Pytorch의 Autograd(자동미분) 연산 가능 [[참고](https://blog.naver.com/PostView.nhn?blogId=qbxlvnf11&logNo=221558405051)]

#### Tensors 초기화

In [21]:
# 초기화 되지 않은 행렬 생성
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.1704e-41],
        [0.0000e+00, 2.2369e+08, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [       nan,        nan, 1.5043e-07]])


In [22]:
# 0~1 사이에서 랜덤으로 초기화된 행렬 생성
x = torch.rand(5, 3)
print(x)

tensor([[0.4759, 0.2704, 0.1562],
        [0.4553, 0.9772, 0.9364],
        [0.9394, 0.5083, 0.5812],
        [0.5779, 0.8068, 0.7123],
        [0.2170, 0.6800, 0.4497]])


In [23]:
# Standard Normal Distribution 에서 랜덤으로 초기화된 행렬 생성
x = torch.randn(5, 3)
print(x)

tensor([[ 8.0003e-01,  1.3656e+00, -1.8330e+00],
        [-1.6199e+00, -2.3794e+00,  1.5698e+00],
        [ 1.0617e+00, -7.2121e-02, -5.6824e-01],
        [-6.5241e-01, -1.2114e+00,  2.3988e-01],
        [ 8.3874e-02, -1.9533e-01, -1.1724e-03]])


In [24]:
# 값 지정하여 행렬 생성
x = torch.tensor([1.2, 2.4])
print(x)

tensor([1.2000, 2.4000])


#### Tensor 연산

In [25]:
# 덧셈
x = torch.randn(5, 3)
y = torch.randn(5, 3)
print(x, '\n', y, '\n', x+y) # x+y = torch.add(x, y)

tensor([[-0.0465,  0.5141, -0.4902],
        [-1.3471,  0.0055,  1.8803],
        [ 0.1811,  1.9931,  0.7980],
        [ 0.8071,  0.7712, -0.9901],
        [-0.7625,  0.1849,  0.5295]]) 
 tensor([[ 0.2590,  0.8608,  0.6949],
        [ 0.4155,  1.7129,  1.3899],
        [-0.6229, -1.7529,  0.9486],
        [-0.0582, -0.6595,  0.9863],
        [ 0.5268,  0.2669,  1.0985]]) 
 tensor([[ 0.2126,  1.3749,  0.2047],
        [-0.9316,  1.7183,  3.2702],
        [-0.4417,  0.2402,  1.7466],
        [ 0.7489,  0.1118, -0.0038],
        [-0.2357,  0.4517,  1.6280]])


#### Tensor 사이즈

In [26]:
# Size 확인
x = torch.randn(4, 4)
print(x.size())

torch.Size([4, 4])


In [27]:
# Resize - reshape: any tensor
x = torch.randn(4, 4)
y = x.reshape(16)
z = x.reshape(-1, 2)
print("by resize: ", x.size(), y.size(), z.size())

# Resize - view: only for contiguous tensors
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 2)
print("by view: ", x.size(), y.size(), z.size())

by resize:  torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])
by view:  torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


#### Tensor, Numpy 변환

In [28]:
# Tensor to Numpy
a = torch.ones(5)
b = a.numpy()
print(a, type(a))
print(b, type(b))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [29]:
# Numpy to Tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a, type(a))
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [30]:
# GPU 연산을 위한 CUDA Tensor
a = torch.ones(5)
# b = a.to(device="cudo:0")

#### Tensor Autograd  
requires_grad 를 true로 세팅하면, 텐서의 모든 연산에 대한 추적 가능  
이를 통해 forward propagation 후 .backward() 호출 시 모든 gradient를 자동으로 계산

In [31]:
x = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True) # default requires_grad for input data: False (whereas default requires_grad for each layer is True)
y = (x+2)**2*3
print(y)

out = y.mean()
print(out)

out.backward()
print(x.grad)

tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)
tensor(64.5000, grad_fn=<MeanBackward0>)
tensor([[4.5000, 6.0000],
        [7.5000, 9.0000]])


$\because {dout\over dx_i} = {dout \over dy} * {dy \over dx_i} = {1 \over 4}*6(x_i+2) = {3\over2}(x_i+2) \hspace{1cm}$
as ${dout \over dy} = {1 \over 4}, {dy \over dx_i} = 6(x_i+2)$

### 1.2 PyTorch Project 구조

#### 1. Load Data

In [32]:
import torchvision # to download 'CIFAR10' dataset
import torchvision.transforms as transforms # to manipulate input data

In [33]:
train_data = torchvision.datasets.CIFAR10(root='./datasets', 
                                          train=True, 
                                          transform=transforms.ToTensor(), 
                                          download=True)

Files already downloaded and verified


In [34]:
# cf) check for the data
image, label = train_data[0]
print(len(train_data), image.size(), label)

50000 torch.Size([3, 32, 32]) 6


#### 2. Define Dataloader
define dataloader (when iters loop, dataloader loads data from queue)

In [35]:
import torch

In [36]:
data_loader = torch.utils.data.DataLoader(dataset=train_data, 
                                          batch_size=64,
                                          shuffle=True)

In [37]:
# cf) check how data_loader works
print(len(data_loader))
for idx, (images, labels) in enumerate(data_loader):
    if idx == 3:
        break
    print(images.size(), labels)

782
torch.Size([64, 3, 32, 32]) tensor([4, 0, 0, 1, 2, 7, 9, 2, 0, 5, 1, 2, 6, 1, 7, 2, 3, 9, 2, 7, 9, 8, 3, 0,
        8, 1, 5, 1, 6, 0, 8, 7, 2, 9, 3, 1, 3, 1, 0, 9, 1, 6, 8, 0, 6, 0, 0, 5,
        2, 7, 9, 8, 4, 5, 6, 3, 0, 9, 7, 8, 2, 3, 2, 1])
torch.Size([64, 3, 32, 32]) tensor([2, 3, 5, 8, 3, 8, 6, 4, 6, 2, 9, 7, 8, 4, 5, 6, 0, 7, 9, 2, 7, 2, 2, 9,
        9, 8, 7, 9, 6, 6, 0, 4, 8, 5, 5, 3, 6, 1, 8, 8, 6, 2, 7, 5, 5, 9, 2, 3,
        7, 4, 0, 3, 5, 3, 6, 1, 3, 1, 3, 5, 8, 4, 1, 0])
torch.Size([64, 3, 32, 32]) tensor([2, 9, 9, 9, 3, 6, 9, 7, 0, 2, 7, 7, 5, 7, 8, 6, 9, 7, 0, 5, 7, 9, 7, 3,
        6, 5, 3, 7, 3, 8, 3, 2, 3, 3, 0, 8, 6, 4, 3, 2, 2, 8, 9, 1, 8, 0, 8, 0,
        6, 0, 6, 4, 4, 6, 2, 3, 9, 0, 9, 9, 7, 5, 1, 5])


#### 3. Define Model

In [38]:
import torch.nn as nn
import torch.nn.functional as F

In [39]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(3, 6, 5),
            nn.BatchNorm2d(6),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)
        )
        self.fc = nn.Linear(6*14*14, 10) # 10 final nodes as CIFAR10 dataset has 10 classes
    
    def forward(self, x):
        out = self.layer1(x)
        out = out.reshape(out.size(0), -1)
        out = self.fc(out)
        return out
    
model = Net()

In [40]:
# cf) check which layers constitute Network
print(model)

Net(
  (layer1): Sequential(
    (0): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
    (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc): Linear(in_features=1176, out_features=10, bias=True)
)


In [41]:
# cf) check how data passes through the Network
data_iter = iter(data_loader)
images, labels = data_iter.next() # only get one mini-batch
outputs = model(images)
print(outputs.size(), '\n', outputs[0], '\n', outputs[0].tolist().index(max(outputs[0])))

torch.Size([64, 10]) 
 tensor([ 0.0212,  0.2625,  0.1453, -0.3778, -0.3433,  0.0587,  0.7294, -0.2470,
         0.1062,  0.5463], grad_fn=<SelectBackward>) 
 6


#### 4. Set Loss & Optimizer

In [42]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

#### 5. Train / Test

In [43]:
epochs = 1
for epoch in range(epochs):
    for i, (images, labels) in enumerate(data_loader):
        # Forward Propagate
        outputs = model(images)
        
        # Get Loss, Compute Gradient, Update Parameters
        loss = criterion(outputs, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if i%50 == 0 or i+1==len(data_loader):
            print('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'.format(epoch+1, epochs, i+1, len(data_loader), loss.item()))
        

Epoch [1/1], Step [1/782], Loss: 2.4780
Epoch [1/1], Step [51/782], Loss: 2.2106
Epoch [1/1], Step [101/782], Loss: 2.1133
Epoch [1/1], Step [151/782], Loss: 1.9809
Epoch [1/1], Step [201/782], Loss: 1.8713
Epoch [1/1], Step [251/782], Loss: 1.9439
Epoch [1/1], Step [301/782], Loss: 1.9779
Epoch [1/1], Step [351/782], Loss: 1.9133
Epoch [1/1], Step [401/782], Loss: 1.9166
Epoch [1/1], Step [451/782], Loss: 1.8785
Epoch [1/1], Step [501/782], Loss: 1.8947
Epoch [1/1], Step [551/782], Loss: 1.8191
Epoch [1/1], Step [601/782], Loss: 1.9819
Epoch [1/1], Step [651/782], Loss: 1.8301
Epoch [1/1], Step [701/782], Loss: 1.8927
Epoch [1/1], Step [751/782], Loss: 1.8470
Epoch [1/1], Step [782/782], Loss: 1.9874


#### 6. Save & Visualization

In [44]:
torch.save(model.state_dict(), 'model.ckpt')

In [45]:
# cf) check the saved model
!ls

datasets            intro_pytorch.ipynb intro_pytorch.py    model.ckpt


<hr>