# PyTorch 개론 (+Google Colab 사용법)
<hr>

cf. Google Colab: [[링크](https://colab.research.google.com/notebooks/welcome.ipynb)] [[사용법](https://drive.google.com/file/d/11B7cjkW0KVMZv-yqxHDhg0TUE3CESYSx/view)]

## 0. Basic Python

### 0.1 자료형과 연산

#### 숫자형

In [1]:
a = 10
b = 1.2
print(a, b)
print(a+b, a-b, a*b, a/b)

10 1.2
11.2 8.8 12.0 8.333333333333334


#### 문자열

In [2]:
quote = "Life is too short,"
print(quote, "Python is fast") 

Life is too short, Python is fast


#### 리스트 / 튜플

* 리스트

In [3]:
a = [1, 2, 'Life', ['a', 'b', 'c']]

In [4]:
print(a[0]) 

1


In [5]:
print(a[-1]) 


['a', 'b', 'c']


In [6]:
print(a[-1][1]) 

b


In [7]:
print(a[0:2]) 

[1, 2]


In [8]:
a.append('short') 
a.insert(2, 3)
print(a)

[1, 2, 3, 'Life', ['a', 'b', 'c'], 'short']


* 튜플: 리스트와 비슷하지만 요소값 생성, 삭제, 수정이 불가

#### 딕셔너리 / 집합

In [9]:
dic = {'key': 'value', '류현진': '야구', '손흥민': '축구'}

In [10]:
print(dic['류현진']) 

야구


In [11]:
print(dic.keys())

dict_keys(['key', '류현진', '손흥민'])


In [12]:
print(dic.values())

dict_values(['value', '야구', '축구'])


In [13]:
dic['new key'] = 'new value' 
print(dic)

{'key': 'value', '류현진': '야구', '손흥민': '축구', 'new key': 'new value'}


### 0.2 제어문

#### if 문

In [14]:
a = [1,2,3]
if a[1]%2==0:
    print("{} is even number".format(a[1]))
elif a[1]%2==1:
    print("{} is odd number".format(a[1]))
else:
    print("Impossible")

2 is even number


#### for 문

In [15]:
for i in range(0, 3):
    print(i)

0
1
2


#### while 문

In [16]:
a = 0
while True:
    if a == 3:
        break
    print(a) 
    a +=1

0
1
2


### 0.3 함수 / 클래스

#### 함수

In [17]:
def square_sum(a, b):
    squared_a = a**2
    squared_b = b**2
    return squared_a + squared_b

c = square_sum(3, 4)
print(c)

25


#### 클래스 

In [18]:
class Calculator():
    def __init__(self):
        self.description = "Example for initializing a Class"
        self.result = 0

    def add(self, num1, numb2):
        if type(num1) == int and type(numb2) == int:
            self.result = self.result + num1 + numb2
            return self.result
        else:
            raise Exception

cal = Calculator()
print(cal.description)
print(cal.add(10, 20))

Example for initializing a Class
30


### 0.4 Packages

#### import

In [19]:
import numpy as np
a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


<hr>

## 1. PyTorch

### 1.1 Tensors / Numpy

In [20]:
import torch
import numpy as np

#### Tensors / Numpy / Python List
* Python List: 행렬연산을 위해 for 문을 사용  
* Numpy: 조건에 따라 차원이 다른 배열간의 연산을 가능하게 하는 Broadcasting을 사용하여 연산가능  
* Tensor: pytorch의 자료형으로 numpy배열과 비슷하나, GPU에서의 연산이 가능하고, Pytorch의 Autograd(자동미분) 연산 가능 [[참고](https://blog.naver.com/PostView.nhn?blogId=qbxlvnf11&logNo=221558405051)]

#### Tensors 초기화

In [21]:
# 초기화 되지 않은 행렬 생성
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 4.6566e-10, 0.0000e+00],
        [4.6566e-10, 7.3348e+28, 6.1425e+28],
        [7.1441e+31, 6.9987e+22, 7.8675e+34],
        [4.7418e+30, 5.9663e-02, 7.0374e+22],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [22]:
# 0~1 사이에서 랜덤으로 초기화된 행렬 생성
x = torch.rand(5, 3)
print(x)

tensor([[0.8355, 0.5548, 0.2035],
        [0.2825, 0.7910, 0.1439],
        [0.3299, 0.6695, 0.1408],
        [0.0692, 0.9165, 0.9834],
        [0.0442, 0.1277, 0.4568]])


In [23]:
# Standard Normal Distribution 에서 랜덤으로 초기화된 행렬 생성
x = torch.randn(5, 3)
print(x)

tensor([[-1.5779, -1.2640,  0.2894],
        [-0.6126,  0.4374, -1.1763],
        [-0.5549, -0.6365,  2.2966],
        [ 0.7137, -1.9657,  1.2797],
        [ 0.3965,  0.6895,  0.2107]])


In [24]:
# 값 지정하여 행렬 생성
x = torch.tensor([1.2, 2.4])
print(x)

tensor([1.2000, 2.4000])


#### Tensor 연산

In [25]:
# 덧셈
x = torch.randn(5, 3)
y = torch.randn(5, 3)
print(x, '\n', y, '\n', x+y) # x+y = torch.add(x, y)

tensor([[-0.3289, -0.0628,  1.2464],
        [-0.1202,  1.5995,  0.0941],
        [-1.1099, -1.1445,  0.9576],
        [-0.8153, -1.2154,  0.7452],
        [-0.1476, -0.7679, -0.9896]]) 
 tensor([[-0.2256,  0.4038,  0.1180],
        [-0.0797,  1.5446,  0.4062],
        [-0.7127,  1.6398, -0.4783],
        [-0.9743, -1.1191,  1.6526],
        [ 1.0673, -1.1267,  1.0245]]) 
 tensor([[-0.5545,  0.3411,  1.3644],
        [-0.1999,  3.1441,  0.5003],
        [-1.8226,  0.4953,  0.4793],
        [-1.7897, -2.3345,  2.3978],
        [ 0.9198, -1.8945,  0.0349]])


#### Tensor 사이즈

In [26]:
# Size 확인
x = torch.randn(4, 4)
print(x.size())

torch.Size([4, 4])


In [31]:
# Resize - view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

# Resize - reshape

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### Tensor, Numpy 변환

In [32]:
# Tensor to Numpy
a = torch.ones(5)
b = a.numpy()
print(a, type(a))
print(b, type(b))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [33]:
# Numpy to Tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a, type(a))
print(b, type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [34]:
# GPU 연산을 위한 CUDA Tensor
a = torch.ones(5)
# b = a.to(device="cudo:0")

#### Tensor Autograd  
.requires_grad 를 true로 세팅하면, 텐서의 모든 연산에 대한 추적 가능  
이를 통해 forward propagation 후 .backward() 호출 시 모든 gradient를 자동으로 계산

In [35]:
x = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True) # default requires_grad for input data: False (whereas default requires_grad for each layer is True)
y = (x+2)**2*3
print(y)

out = y.mean()
print(out)

out.backward()
print(x.grad)

tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)
tensor(64.5000, grad_fn=<MeanBackward0>)
tensor([[4.5000, 6.0000],
        [7.5000, 9.0000]])


$\because {dout\over dx_i} = {dout \over dy} * {dy \over dx_i} = {1 \over 4}*6(x_i+2) = {3\over2}(x_i+2) \hspace{1cm}$
as ${dout \over dy} = {1 \over 4}, {dy \over dx_i} = 6(x_i+2)$

### 1.2 PyTorch Project 구조

#### 1. Load Data

In [36]:
import torchvision # to download 'CIFAR10' dataset
import torchvision.transforms as transforms # to manipulate input data

In [37]:
train_data = torchvision.datasets.CIFAR10(root='./datasets', 
                                          train=True, 
                                          transform=transforms.ToTensor(), 
                                          download=True)

Files already downloaded and verified


In [38]:
# cf) check for the data
image, label = train_data[0]
print(len(train_data), image.size(), label)

50000 torch.Size([3, 32, 32]) 6


#### 2. Define Dataloader
define dataloader (when iters loop, dataloader loads data from queue)

In [39]:
import torch

In [40]:
data_loader = torch.utils.data.DataLoader(dataset=train_data, 
                                          batch_size=64,
                                          shuffle=True)

In [41]:
# cf) check how data_loader works
print(len(data_loader))
for idx, (images, labels) in enumerate(data_loader):
    if idx == 3:
        break
    print(images.size(), labels)

782
torch.Size([64, 3, 32, 32]) tensor([3, 2, 2, 1, 5, 1, 5, 2, 1, 8, 7, 2, 9, 5, 5, 8, 7, 8, 1, 3, 7, 7, 7, 2,
        8, 8, 3, 7, 2, 5, 0, 5, 0, 3, 0, 6, 2, 5, 9, 1, 2, 1, 9, 4, 9, 0, 2, 6,
        7, 4, 2, 2, 0, 9, 5, 4, 8, 0, 9, 1, 5, 3, 2, 1])
torch.Size([64, 3, 32, 32]) tensor([9, 7, 4, 3, 7, 0, 7, 0, 8, 0, 1, 2, 6, 9, 6, 0, 2, 7, 8, 2, 4, 9, 7, 5,
        2, 2, 3, 5, 5, 9, 5, 6, 3, 6, 8, 8, 1, 1, 1, 1, 8, 8, 0, 2, 4, 4, 2, 7,
        9, 9, 6, 9, 4, 1, 9, 6, 6, 5, 7, 6, 1, 8, 6, 0])
torch.Size([64, 3, 32, 32]) tensor([3, 4, 2, 0, 2, 8, 0, 7, 6, 9, 9, 8, 9, 0, 0, 4, 2, 7, 0, 4, 2, 0, 1, 5,
        7, 4, 4, 2, 8, 8, 5, 4, 5, 9, 8, 0, 8, 3, 7, 0, 6, 0, 8, 8, 2, 5, 3, 8,
        8, 7, 1, 8, 9, 1, 2, 6, 5, 2, 4, 4, 2, 0, 3, 9])


#### 2. Define Model

In [42]:
import torch.nn as nn
import torch.nn.functional as F

In [43]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(3, 6, 5),
            nn.BatchNorm2d(6),
            nn.ReLU(),
            nn.MaxPool2d(2, 2)
        )
        self.fc = nn.Linear(6*14*14, 10) # 10 final nodes as CIFAR10 dataset has 10 classes
    
    def forward(self, x):
        out = self.layer1(x)
        out = out.reshape(out.size(0), -1)
        out = self.fc(out)
        return out
    
model = Net()

In [44]:
# cf) check which layers constitute Network
print(model)

Net(
  (layer1): Sequential(
    (0): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
    (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (fc): Linear(in_features=1176, out_features=10, bias=True)
)


In [45]:
# cf) check how data passes through the Network
data_iter = iter(data_loader)
images, labels = data_iter.next() # only get one mini-batch
outputs = model(images)
print(outputs.size(), '\n', outputs[0], '\n', outputs[0].tolist().index(max(outputs[0])))

torch.Size([64, 10]) 
 tensor([-0.0841,  0.3907, -0.7210,  0.6113,  0.2720,  0.6076,  0.6780, -0.4594,
         0.1557, -0.0570], grad_fn=<SelectBackward>) 
 6


#### 3. Set Loss & Optimizer

In [47]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

#### 4. Train

In [49]:
epochs = 1
for epoch in range(epochs):
    for i, (images, labels) in enumerate(data_loader):
        # Forward Propagate
        outputs = model(images)
        
        # Get Loss, Compute Gradient, Update Parameters
        loss = criterion(outputs, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        print('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'.format(epoch+1, epochs, i+1, len(data_loader), loss.item()))
        

Epoch [1/1], Step [1/782], Loss: 1.8431
Epoch [1/1], Step [2/782], Loss: 1.9104
Epoch [1/1], Step [3/782], Loss: 1.8889
Epoch [1/1], Step [4/782], Loss: 1.9624
Epoch [1/1], Step [5/782], Loss: 1.9022
Epoch [1/1], Step [6/782], Loss: 1.9324
Epoch [1/1], Step [7/782], Loss: 1.6998
Epoch [1/1], Step [8/782], Loss: 1.8164
Epoch [1/1], Step [9/782], Loss: 1.8314
Epoch [1/1], Step [10/782], Loss: 1.8615
Epoch [1/1], Step [11/782], Loss: 1.9456
Epoch [1/1], Step [12/782], Loss: 1.7522
Epoch [1/1], Step [13/782], Loss: 1.9433
Epoch [1/1], Step [14/782], Loss: 1.8207
Epoch [1/1], Step [15/782], Loss: 1.9919
Epoch [1/1], Step [16/782], Loss: 2.0210
Epoch [1/1], Step [17/782], Loss: 1.8945
Epoch [1/1], Step [18/782], Loss: 1.9919
Epoch [1/1], Step [19/782], Loss: 1.7136
Epoch [1/1], Step [20/782], Loss: 1.9824
Epoch [1/1], Step [21/782], Loss: 1.9556
Epoch [1/1], Step [22/782], Loss: 1.9255
Epoch [1/1], Step [23/782], Loss: 1.8711
Epoch [1/1], Step [24/782], Loss: 1.9328
Epoch [1/1], Step [25/782

Epoch [1/1], Step [202/782], Loss: 1.9329
Epoch [1/1], Step [203/782], Loss: 1.7495
Epoch [1/1], Step [204/782], Loss: 1.7852
Epoch [1/1], Step [205/782], Loss: 1.7342
Epoch [1/1], Step [206/782], Loss: 1.6246
Epoch [1/1], Step [207/782], Loss: 1.9064
Epoch [1/1], Step [208/782], Loss: 1.8164
Epoch [1/1], Step [209/782], Loss: 1.8830
Epoch [1/1], Step [210/782], Loss: 1.9131
Epoch [1/1], Step [211/782], Loss: 1.7249
Epoch [1/1], Step [212/782], Loss: 1.7671
Epoch [1/1], Step [213/782], Loss: 1.7827
Epoch [1/1], Step [214/782], Loss: 1.8729
Epoch [1/1], Step [215/782], Loss: 1.7339
Epoch [1/1], Step [216/782], Loss: 1.7179
Epoch [1/1], Step [217/782], Loss: 1.9003
Epoch [1/1], Step [218/782], Loss: 1.7990
Epoch [1/1], Step [219/782], Loss: 1.9010
Epoch [1/1], Step [220/782], Loss: 1.9363
Epoch [1/1], Step [221/782], Loss: 1.7082
Epoch [1/1], Step [222/782], Loss: 1.7400
Epoch [1/1], Step [223/782], Loss: 1.7633
Epoch [1/1], Step [224/782], Loss: 1.9057
Epoch [1/1], Step [225/782], Loss:

Epoch [1/1], Step [400/782], Loss: 1.8175
Epoch [1/1], Step [401/782], Loss: 1.7654
Epoch [1/1], Step [402/782], Loss: 1.7492
Epoch [1/1], Step [403/782], Loss: 1.7454
Epoch [1/1], Step [404/782], Loss: 1.9838
Epoch [1/1], Step [405/782], Loss: 1.8516
Epoch [1/1], Step [406/782], Loss: 1.9333
Epoch [1/1], Step [407/782], Loss: 1.7862
Epoch [1/1], Step [408/782], Loss: 1.7956
Epoch [1/1], Step [409/782], Loss: 1.7771
Epoch [1/1], Step [410/782], Loss: 1.9314
Epoch [1/1], Step [411/782], Loss: 1.8072
Epoch [1/1], Step [412/782], Loss: 1.8069
Epoch [1/1], Step [413/782], Loss: 1.6437
Epoch [1/1], Step [414/782], Loss: 1.8694
Epoch [1/1], Step [415/782], Loss: 1.6547
Epoch [1/1], Step [416/782], Loss: 1.9138
Epoch [1/1], Step [417/782], Loss: 1.5264
Epoch [1/1], Step [418/782], Loss: 1.5880
Epoch [1/1], Step [419/782], Loss: 1.8529
Epoch [1/1], Step [420/782], Loss: 1.8082
Epoch [1/1], Step [421/782], Loss: 1.6663
Epoch [1/1], Step [422/782], Loss: 1.8213
Epoch [1/1], Step [423/782], Loss:

Epoch [1/1], Step [601/782], Loss: 1.6928
Epoch [1/1], Step [602/782], Loss: 1.8503
Epoch [1/1], Step [603/782], Loss: 1.7075
Epoch [1/1], Step [604/782], Loss: 1.7075
Epoch [1/1], Step [605/782], Loss: 1.9455
Epoch [1/1], Step [606/782], Loss: 1.7661
Epoch [1/1], Step [607/782], Loss: 1.5903
Epoch [1/1], Step [608/782], Loss: 1.8007
Epoch [1/1], Step [609/782], Loss: 1.7519
Epoch [1/1], Step [610/782], Loss: 1.7660
Epoch [1/1], Step [611/782], Loss: 1.5880
Epoch [1/1], Step [612/782], Loss: 1.6895
Epoch [1/1], Step [613/782], Loss: 1.5041
Epoch [1/1], Step [614/782], Loss: 1.6161
Epoch [1/1], Step [615/782], Loss: 1.6854
Epoch [1/1], Step [616/782], Loss: 1.7065
Epoch [1/1], Step [617/782], Loss: 1.7604
Epoch [1/1], Step [618/782], Loss: 1.7296
Epoch [1/1], Step [619/782], Loss: 1.5800
Epoch [1/1], Step [620/782], Loss: 1.7018
Epoch [1/1], Step [621/782], Loss: 1.7299
Epoch [1/1], Step [622/782], Loss: 1.8076
Epoch [1/1], Step [623/782], Loss: 1.7089
Epoch [1/1], Step [624/782], Loss:

#### 5. Save & Visualization

In [50]:
torch.save(model.state_dict(), 'model.ckpt')

In [51]:
# cf) check the saved model
!ls

datasets            intro_pytorch.ipynb model.ckpt


<hr>